bhealth/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include('client.urls', namespace='client')),
    url(r'^product/', include('product.urls', namespace='product'))
)

#authentification
urlpatterns += patterns('',
    url(r'^', include('bhealth_auth.urls', namespace='bhealth_auth'))
)

#social_authentification
urlpatterns += patterns('',
    url(r'', include('social.apps.django_app.urls', namespace='social'))
)

bhealth_auth/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('bhealth_auth.views',

    url(r'^logout/$', 'logout', name='logout'),
    url(r'^$', 'login', name='login'),

)

client/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^(?P<pk>\d+)/$', 'client.views.profile', name='profile'),

)

product/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',

    url(r'^search/', 'product.views.search', name='search'),


)

client/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    gender_choices = (
        (1, 'Мужчина'),
        (2, 'Женщина'),
    )
    activity_choice = (
        (1, 'Пассивный'),
        (2, 'Легкий'),
        (3, 'Активный'),
        (4, 'Очень активный'),
    )
    goal_choice = (
        (1, 'Похудеть'),
        (2, 'Остаться в форме'),
        (3, 'Набрать вес'),
    )
    coach_choices = (
        (1, 'Есть'),
        (2, 'Нет'),
    )
    user = models.OneToOneField(User, related_name='client')
    unique_id = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255, blank=True)
    gender = models.IntegerField(choices=gender_choices, blank=True, null=True)
    height = models.FloatField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    activity = models.IntegerField(choices=activity_choice, blank=True, null=True)
    count_training_to_week = models.IntegerField(blank=True, null=True)
    count_minute_to_training = models.IntegerField(blank=True, null=True)
    goal = models.IntegerField(choices=goal_choice, blank=True, null=True)
    have_a_coach = models.IntegerField(choices=coach_choices, blank=True)
    avatar = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.user.email or self.unique_id


class ClientCalendar(models.Model):
    client_id = models.ForeignKey(Client)
    date = models.DateField()

product/models.py
from django.db import models
from client.models import ClientCalendar


class Food(models.Model):
    name = models.CharField(max_length=200)
    preparing_method = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Блюда'


class FoodCalendar(models.Model):
    food_time_choices = (
        (1, 'breakfast'),
        (2, 'lunch'),
        (3, 'dinner'),
        (4, 'supper'),
    )
    calendar_id = models.ForeignKey(ClientCalendar)
    food_id = models.ForeignKey(Food)
    weight = models.FloatField()
    food_time = models.IntegerField(choices=food_time_choices)


class Product(models.Model):
    name = models.CharField(max_length=200)
    kkal = models.FloatField()
    b = models.FloatField()
    j = models.FloatField()
    u = models.FloatField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Продукты'

class FoodToProduct(models.Model):
    food_id = models.ForeignKey(Food)
    product_id = models.ForeignKey(Product)
    product_weight = models.IntegerField()

training/models.py
from django.db import models
from client.models import ClientCalendar


class Muscle(models.Model):
    name = models.CharField(max_length=200)


class Training(models.Model):
    type_choices = (
        (1,'',),
        (2,'',),
        (3,'',),
        (4,'',),
    )
    equipment_choices = (
        (1,'',),
        (2,'',),
        (3,'',),
        (4,'',),
    )
    difficulty_choices = (
        (1,'',),
        (2,'',),
        (3,'',),
        (4,'',),
    )
    name = models.CharField(max_length=200)
    tr_type = models.IntegerField(choices=type_choices)
    equipment = models.IntegerField(choices=equipment_choices)
    difficulty = models.IntegerField(choices=difficulty_choices)
    description = models.TextField()

class TrainingToMuscle(models.Model):
    muscle = models.ForeignKey(Muscle)
    training = models.ForeignKey(Training)
    is_primary = models.IntegerField()


class TrainingCalendar(models.Model):
    calendar_id = models.ForeignKey(ClientCalendar)
    training_id = models.ForeignKey(Training)

client/forms.py
from django.forms import ModelForm

bhealth_auth/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
from bhealth_auth.pipeline import create_user
from client.models import Client


def login(request):
    if request.method == 'GET':
        if request.user.is_superuser:
            return HttpResponseRedirect('/admin/')
        if request.user.is_authenticated():
            return HttpResponseRedirect(
                reverse('client:profile',
                        kwargs={'pk': get_object_or_404(Client, unique_id=request.user.client.unique_id).pk}
                        )
            )

        return render(request, 'bhealth_auth/login.html')


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('bhealth_auth:login'))


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        '''
        add form validation check and else
        '''
        create_user(**{'unique_id': username,'password': password})

client/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from client.models import Client
from client.decorators import profile_access
from django.contrib.auth.models import User

@profile_access
def profile(request, pk):
    client = Client.objects.get(pk=pk)
    return render(request, 'client/profile_base.html', {'client':client})

product/views.py
from django.shortcuts import render, render_to_response
from product.models import Product
import json


def search(request):
    if request.is_ajax():
        search_text = request.POST['search_text']
        result = Product.objects.filter(name__icontains=search_text)
        return render_to_response('client/product_search.html', {'result':result})

training/views.py
from django.shortcuts import render

# Create your views here.

templates/bhealth_auth/login.html
{% load backend_utils %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/static/css/zabuto_calendar.css">
    <link rel="stylesheet" type="text/css" href="/static/js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="/static/lineicons/style.css">    
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet">
    <script src="/static/js/chart-master/Chart.js"></script>
  </head>

  <body>
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  <div id="login-page">
	  	<div class="container">

		      <form class="form-login" action="index.html">
		        <h2 class="form-login-heading">sign in now</h2>
		        <div class="login-wrap">
		            <input type="text" class="form-control" placeholder="User ID" autofocus>
		            <br>
		            <input type="password" class="form-control" placeholder="Password">
		            <label class="checkbox">
		                <span class="pull-right">
		                    <a data-toggle="modal" href="login.html#myModal"> Forgot Password?</a>

		                </span>
		            </label>
		            <button class="btn btn-theme btn-block" href="index.html" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
		            <hr>

		            <div class="login-social-link centered">
		            <p>or you can sign in via your social network</p>
		                <a class="btn btn-danger" type="submit" href="{% url 'social:begin' 'google-oauth2' %}"><i class="fa fa-google-plus"></i> Google</a>
		                <a class="btn btn-danger" type="submit" href="{% url 'social:begin' 'vk-oauth2' %}"><i class="fa fa-vk"></i> VKontakte</a>
		            </div>
		            <div class="registration">
		                Don't have an account yet?<br/>
		                <a class="" href="#">
		                    Create an account
		                </a>
		            </div>

		        </div>

		          <!-- Modal -->
		          <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
		              <div class="modal-dialog">
		                  <div class="modal-content">
		                      <div class="modal-header">
		                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		                          <h4 class="modal-title">Forgot Password ?</h4>
		                      </div>
		                      <div class="modal-body">
		                          <p>Enter your e-mail address below to reset your password.</p>
		                          <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">

		                      </div>
		                      <div class="modal-footer">
		                          <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
		                          <button class="btn btn-theme" type="button">Submit</button>
		                      </div>
		                  </div>
		              </div>
		          </div>
		          <!-- modal -->

		      </form>

	  	</div>
	  </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="/static/js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("assets/img/login-bg.jpg", {speed: 500});
    </script>


  </body>
</html>

templates/client/product_search.html
<p><select size="{{ result.count }}">
{% for prod in result %}

    <option value="Чебурашка">{{ prod.name }}</option>


{% endfor %}
</select></p>

templates/client/profile_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>BHealth</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/static/css/zabuto_calendar.css">
    <link rel="stylesheet" type="text/css" href="/static/js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="/static/lineicons/style.css">
    
    <!-- Custom styles for this template -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet">

    <script src="/static/js/chart-master/Chart.js"></script>
  </head>

  <body>

  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="{% url 'bhealth_auth:login' %}" class="logo"><b>BHEALTH</b></a>
            <!--logo end-->


            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><a class="logout" href="{% url 'bhealth_auth:logout' %}">Выйти</a></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              
              	  <p class="centered"><a href="{% url 'client:profile' client.pk %}"><img src="{{ client.avatar }}" class="img-circle" width="60"></a></p>
              	  <h5 class="centered">{{ client.name }}</h5>
              	  	
                  <li class="mt">
                      <a class="active" href="index.html">
                          <i class="fa fa-dashboard"></i>
                          <span>Основное</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>Тренировки</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="general.html">General</a></li>
                          <li><a  href="buttons.html">Buttons</a></li>
                          <li><a  href="panels.html">Panels</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-cogs"></i>
                          <span>Питание</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="calendar.html">Calendar</a></li>
                          <li><a  href="gallery.html">Gallery</a></li>
                          <li><a  href="todo_list.html">Todo List</a></li>
                      </ul>
                  </li>


                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class=" fa fa-bar-chart-o"></i>
                          <span>Прогресс</span>
                      </a>
                  </li>

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">

              <div class="row">
                  <div class="col-lg-9 main-chart">
                  <!-- SEARCH TEST -->
                      {% csrf_token %}
                      <input type="text" class="search" id="bhealth_product_search">
                      <div id="product_search_result">

                      </div>
                  <!-- END SEARCH TEST -->
                  </div><!-- /col-lg-9 END SECTION MIDDLE -->
                  
                  
      <!-- **********************************************************************************************************************************************************
      RIGHT SIDEBAR CONTENT
      *********************************************************************************************************************************************************** -->                  
                  
                  <div class="col-lg-3 ds">
                    <!--COMPLETED ACTIONS DONUTS CHART-->
						<h3>НАПОМИНАНИЯ</h3>
                                        
                      <!-- First Action -->
                      <div class="desc">
                      	<div class="thumb">
                      		<span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
                      	</div>
                      	<div class="details">
                      		<p><muted>2 минуты назад</muted><br/>
                      		   Сегодня у вас тренировка.<br/>
                      		</p>
                      	</div>
                      </div>
                      <!-- Second Action -->
                      <div class="desc">
                      	<div class="thumb">
                      		<span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
                      	</div>
                      	<div class="details">
                      		<p><muted>3 часа назад</muted><br/>
                      		   Следующая тренировка через 3 часа.<br/>
                      		</p>
                      	</div>
                      </div>

                      <!-- CALENDAR-->
                      <div id="calendar" class="mb">
                          <div class="panel darkblue-panel no-margin">
                              <div class="panel-body">
                                  <div id="date-popover" class="popover top" style="cursor: pointer; disadding: block; margin-left: 33%; margin-top: -50px; width: 175px;">
                                      <div class="arrow"></div>
                                      <h3 class="popover-title" style="disadding: none;"></h3>
                                      <div id="date-popover-content" class="popover-content"></div>
                                  </div>
                                      <div id="my-calendar"></div>
                              </div>
                          </div>
                      </div>
                      <!-- / calendar -->
                      
                  </div><!-- /col-lg-3 -->
              </div><!--/row -->
          </section>
      </section>

  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/jquery-1.8.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/static/js/jquery.scrollTo.min.js"></script>
    <script src="/static/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/static/js/jquery.sparkline.js"></script>


    <!--common script for all pages-->
    <script src="/static/js/common-scripts.js"></script>
    
    <script type="text/javascript" src="/static/js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="/static/js/gritter-conf.js"></script>

    <!--script for this page-->
    <script src="/static/js/sparkline-chart.js"></script>
	<script src="/static/js/zabuto_calendar.js"></script>
	
	<script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });
        
            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });
        
        
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
        function myDateFunction(id) {
            var date = $("#" + id).data("date");
            var redirect = window.location.href+date;
            console.log(redirect);
            window.location.href = redirect;
        }
    </script>
  
<script type="text/javascript">


            $('#bhealth_product_search').on('keyup', function(event){
                console.log(1);
                search()
                });

      function search() {
         $.ajax(
                 {
                     url: '/product/search/',
                     type: 'POST',
                     data: {
                            'csrfmiddlewaretoken': '{{csrf_token}}',
                            'search_text': $('#bhealth_product_search').val()
                            },

                     success: function(data) {
                         $('#product_search_result').html(data);
                            }

                 }
         );
     }


</script>
  </body>
</html>